y=(input('Digite algo: '))
print('o tipo primitivo desse valor é:',type(y))
print('so tem espaço?',y.isspace())
print('é um numero?',y.isnumeric())
print('é alfabético?',y.isalpha())
print('é alfanumerico?',y.isalnum())
print('esta apenas em maiusculo?',y.isupper())
print('está apenas em miniscula?',y.islower())
print('está capitalizada?',y.istitle())