n1=float(input('Nota de caderno: '))
n2=float(input('Nota de prova mensal: '))
n3=float(input('Nota de prova bimestral: '))
nc=(n1*1)
pm=(n2*2)
pb=(n3*3)
s=(nc+pm+pb)
r=(s/6)
print('Sua média é: {:.1f}!'.format(r))